### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by gavanderhoorn** [PickNikRobotics/trackjoint#77]
Nice to see this open-sourced, but the license currently says `All rights reserved.`, which makes this package "untouchable".

Will it be BSD [again](https://github.com/PickNikRobotics/trackjoint/commit/ef8459b4518dbd019d0237cc6216ef8eec37eb6c)?

The license blocks in all source files would also need to be updated ([example](https://github.com/PickNikRobotics/trackjoint/blob/250aa4b9c37c113a587521d72425faf6f403e664/src/single_joint_generator.cpp#L1-L7)).

**Comment by AndyZe** [comment]
@gavanderhoorn Yes, my inclination is BSD 3-clause. When PickNik makes MoveIt contributions, that's what we use. Does that work for you? Will make a PR now

**Comment by gavanderhoorn** [comment]
Sure. BSD-3 should be fine.
